import { useMemo, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, BadgeCheck, BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronDown, CircleAlert, ClipboardCheck, FileCheck2, Handshake, LayoutGrid, Users } from 'lucide-react';
import './admin-dashboard.css';

const asDate = value => { if (!value) return null; const date = value.toDate ? value.toDate() : new Date(value); return Number.isNaN(date.getTime()) ? null : date; };
const lower = value => String(value || '').toLowerCase().replace(/_/g, ' ');
const dayLabel = date => date.toLocaleDateString('en-US', { weekday: 'short' });
const shortDate = value => asDate(value)?.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) || 'Date unavailable';
const nameOf = person => person.displayName || person.name || person.email || 'Name not provided';
const initials = name => name.split(/\s+/).slice(0, 2).map(part => part[0]).join('').toUpperCase();
const pendingStatus = value => ['pending', 'pending review', 'submitted', 'in review'].includes(lower(value));
const readable = value => String(value || '').replace(/[_-]/g, ' ').replace(/\b\w/g, letter => letter.toUpperCase());
function Empty({ children }) { return <div className="ops-empty"><span><CheckCircle2 size={17}/></span><p>{children}</p></div>; }

export default function AdminDashboard({ adminName = 'Admin', users = [], referrals = [], applications = [], agreements = [], support = [], activity = [], loading = false, error, onRetry, onNavigate, onOpenRecord }) {
  const [months, setMonths] = useState(4);
  const pendingUsers = users.filter(person => pendingStatus(person.professionalVerificationStatus || person.verificationStatus));
  const approvedUsers = users.filter(person => lower(person.professionalVerificationStatus || person.verificationStatus) === 'approved');
  const pendingApps = applications.filter(item => pendingStatus(item.status));
  const openReferrals = referrals.filter(item => ['open', 'published', 'active', 'live'].includes(lower(item.status)));
  const awaiting = [...pendingUsers.map(item => ({ item, label: nameOf(item), type: 'Credential review', path: 'verification', date: item.verificationSubmittedAt || item.createdAt, icon: BadgeCheck })), ...pendingApps.map(item => ({ item, label: item.applicantName || item.referralTitle || 'Referral application', type: 'Application review', path: 'applications', date: item.submittedAt || item.createdAt, icon: FileCheck2 })), ...support.filter(item => ['open', 'pending', 'in progress'].includes(lower(item.status))).map(item => ({ item, label: item.subject || 'Support request', type: 'Support request', path: 'support', date: item.createdAt, icon: CircleAlert }))].sort((a, b) => (asDate(a.date)?.getTime() || 0) - (asDate(b.date)?.getTime() || 0));
  const recentActivity = [...activity].sort((a, b) => (asDate(b.createdAt)?.getTime() || 0) - (asDate(a.createdAt)?.getTime() || 0)).slice(0, 4);
  const newestPeople = [...users].sort((a, b) => (asDate(b.createdAt)?.getTime() || 0) - (asDate(a.createdAt)?.getTime() || 0)).slice(0, 4);
  const latestReferrals = [...referrals].sort((a, b) => (asDate(b.createdAt)?.getTime() || 0) - (asDate(a.createdAt)?.getTime() || 0)).slice(0, 5);
  const activeAgreements = agreements.filter(item => ['active', 'signed', 'pending signatures'].includes(lower(item.status))).length;
  const chart = useMemo(() => Array.from({ length: 7 }, (_, index) => {
    const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - 6 + index);
    const same = item => asDate(item.submittedAt || item.appliedAt || item.createdAt)?.toDateString() === date.toDateString();
    return { date, day: dayLabel(date), referrals: referrals.filter(item => asDate(item.createdAt)?.toDateString() === date.toDateString()).length, applications: applications.filter(same).length };
  }), [referrals, applications]);
  const chartMax = Math.max(1, ...chart.map(point => point.referrals + point.applications));
  const lastMonths = useMemo(() => Array.from({ length: months }, (_, index) => {
    const date = new Date(); date.setDate(1); date.setMonth(date.getMonth() - (months - index - 1));
    const inMonth = item => { const created = asDate(item.createdAt || item.submittedAt); return created && created.getFullYear() === date.getFullYear() && created.getMonth() === date.getMonth(); };
    return { month: date.toLocaleDateString('en-US', { month: 'short' }), referrals: referrals.filter(inMonth).length, applications: applications.filter(inMonth).length };
  }), [referrals, applications, months]);
  const monthMax = Math.max(1, ...lastMonths.map(point => point.referrals + point.applications));
  const completion = users.length ? Math.round(approvedUsers.length / users.length * 100) : 0;
  const downloadSummary = () => {
    const lines = ['Metric,Count', `Professionals,${users.length}`, `Approved professionals,${approvedUsers.length}`, `Pending credentials,${pendingUsers.length}`, `Referrals,${referrals.length}`, `Applications,${applications.length}`, `Active agreements,${activeAgreements}`];
    const url = URL.createObjectURL(new Blob([lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `agentreferrals-summary-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };

  const metrics = [
    { label: 'Total referrals', value: referrals.length, note: `${applications.length} applications received`, icon: BriefcaseBusiness, path: 'referrals', style: 'primary' },
    { label: 'Applications', value: applications.length, note: `${pendingApps.length} awaiting review`, icon: FileCheck2, path: 'applications' },
    { label: 'Live marketplace', value: openReferrals.length, note: 'Published opportunities', icon: LayoutGrid, path: 'referrals' },
    { label: 'Agreements', value: activeAgreements, note: 'Active or awaiting signature', icon: Handshake, path: 'agreements' },
  ];

  return <div className="ops-dashboard">
    <header className="ops-intro"><div><span className="ops-eyebrow">NETWORK OVERVIEW</span><h1>Welcome back, {adminName.split(' ')[0]}</h1><p>Everything moving across your AgentReferrals network.</p></div><div className="ops-intro-actions"><button className="ops-primary" onClick={() => onNavigate('referrals')}>Manage referrals <ArrowRight size={15}/></button><button className="ops-outline" onClick={() => onNavigate('applications')}><ClipboardCheck size={15}/> Review applications</button></div></header>
    <div className="ops-toolbar"><span className="ops-toolbar-label"><span/> Live workspace overview</span><button onClick={downloadSummary} disabled={loading || !!error}><ArrowDownToLine size={14}/> Download summary</button></div>
    {error ? <div className="ops-load-error"><CircleAlert size={18}/><span><b>Referrals could not be loaded</b><small>{error?.code ? `${String(error.code).split('/').pop()}: ` : ''}{error?.message || 'Check account access, then retry.'}</small></span><button onClick={onRetry}>Try again</button></div> : loading ? <div className="ops-loading" aria-label="Loading dashboard">{Array.from({ length: 6 }, (_, i) => <div key={i}/>)}</div> : <>
      <div className="ops-stat-grid">{metrics.map(({ label, value, note, icon: Icon, path, style }) => <button className={`ops-stat ${style || ''}`} key={label} onClick={() => onNavigate(path)}><span className="ops-stat-top"><i><Icon size={16}/></i><ArrowRight size={16}/></span><small>{label}</small><strong>{value}</strong><span className="ops-stat-note">{note}</span></button>)}</div>
      <div className="ops-grid">
        <section className="ops-panel ops-analytics"><div className="ops-panel-head"><div><span className="ops-eyebrow">ACTIVITY</span><h2>Referral &amp; application activity</h2><p>New records submitted across the last seven days.</p></div><button className="ops-link-button" onClick={() => onNavigate('calendar')}>Open calendar <ArrowRight size={14}/></button></div><div className="ops-chart-legend"><span><i className="referral"/> Referrals</span><span><i className="application"/> Applications</span></div><div className="ops-week-chart">{chart.map(point => { const referralHeight = point.referrals / chartMax * 100; const appHeight = point.applications / chartMax * 100; return <div className="ops-day" key={point.date.toISOString()} aria-label={`${point.day}: ${point.referrals} referrals, ${point.applications} applications`}><div className="ops-day-track"><div className="ops-bars"><span className="ops-bar-referral" style={{ height: `${referralHeight}%` }}/><span className="ops-bar-application" style={{ height: `${appHeight}%` }}/></div><small>{point.referrals + point.applications || ''}</small></div><span className="ops-day-label">{point.day.slice(0, 1)}</span></div>; })}</div></section>
        <section className="ops-panel ops-reminders"><div className="ops-panel-head"><div><span className="ops-eyebrow">NEEDS ATTENTION</span><h2>Review queue</h2></div><b className="ops-count">{awaiting.length}</b></div><p>Items that need an administrator's attention.</p>{awaiting.length ? <div className="ops-reminder-list">{awaiting.slice(0, 4).map(({ item, label, type, path, date, icon: Icon }) => <button key={`${path}-${item.id}`} onClick={() => onNavigate(path)}><i className="ops-reminder-icon"><Icon size={15}/></i><span><b>{label}</b><small>{type}</small></span><time>{shortDate(date)}</time></button>)}</div> : <Empty>You're all caught up. New review items will appear here.</Empty>}<button className="ops-link-button" onClick={() => onNavigate('verification')}>Open verification center <ArrowRight size={14}/></button></section>
        <section className="ops-panel ops-pipeline"><div className="ops-panel-head"><div><span className="ops-eyebrow">MARKETPLACE</span><h2>Recent referrals</h2></div><button className="ops-small-outline" onClick={() => onNavigate('referrals')}>View all <ArrowRight size={13}/></button></div>{latestReferrals.length ? <div className="ops-pipeline-list">{latestReferrals.map(item => <button key={item.id} onClick={() => onOpenRecord('referrals', item)}><span className="ops-pipeline-icon"><BriefcaseBusiness size={15}/></span><span><b>{item.title || 'Referral opportunity'}</b><small>{[item.city, item.state].filter(Boolean).join(', ') || 'Location not provided'}</small></span><time>{shortDate(item.createdAt)}</time></button>)}</div> : <Empty>Posted referral opportunities will appear here.</Empty>}</section>
        <section className="ops-panel ops-team"><div className="ops-panel-head"><div><span className="ops-eyebrow">YOUR NETWORK</span><h2>Team</h2></div><button className="ops-small-outline" onClick={() => onNavigate('users')}>All people <ArrowRight size={13}/></button></div>{newestPeople.length ? <div className="ops-team-list">{newestPeople.map(person => <button key={person.id} onClick={() => onOpenRecord('users', person)}><i className="ops-avatar">{initials(nameOf(person))}</i><span><b>{nameOf(person)}</b><small>{person.brokerageName || person.email || 'Professional'}</small></span><span className="ops-team-status"><i/>{readable(person.accountStatus || 'Active')}</span></button>)}</div> : <Empty>New professionals will appear here.</Empty>}</section>
        <section className="ops-panel ops-monthly"><div className="ops-panel-head"><div><span className="ops-eyebrow">NETWORK GROWTH</span><h2>Monthly activity</h2></div><label><select aria-label="Monthly activity period" value={months} onChange={event => setMonths(Number(event.target.value))}><option value={4}>4 months</option><option value={6}>6 months</option><option value={12}>12 months</option></select><ChevronDown size={12}/></label></div><div className="ops-chart-legend"><span><i className="referral"/> Referrals</span><span><i className="application"/> Applications</span></div><div className="ops-month-chart">{lastMonths.map(point => <div key={point.month} className="ops-month-column"><div className="ops-month-bars"><i className="ops-bar-referral" style={{ height: `${point.referrals / monthMax * 100}%` }}/><i className="ops-bar-application" style={{ height: `${point.applications / monthMax * 100}%` }}/></div><small>{point.month}</small></div>)}</div><button className="ops-link-button" onClick={() => onNavigate('reports')}>Go to analytics <ArrowRight size={14}/></button></section>
        <section className="ops-panel ops-progress"><div><span className="ops-eyebrow">VERIFICATION</span><h2>Credential health</h2></div><div className="ops-progress-ring" style={{ '--progress': `${completion}%` }}><span>{completion}%</span></div><p>{approvedUsers.length} of {users.length} professionals approved.</p><div className="ops-progress-track"><i style={{ width: `${completion}%` }}/></div><button className="ops-link-button" onClick={() => onNavigate('verification')}>Review credentials <ArrowRight size={14}/></button></section>
        <section className="ops-panel ops-activity"><div className="ops-panel-head"><div><span className="ops-eyebrow">LATEST UPDATES</span><h2>Recent activity</h2></div><button className="ops-small-outline" onClick={() => onNavigate('activity')}>View activity <ArrowRight size={13}/></button></div>{recentActivity.length ? <div className="ops-activity-list">{recentActivity.map(item => <button key={item.id} onClick={() => onNavigate('activity')}><i/><span><b>{item.title || item.action || item.type || 'Activity recorded'}</b><small>{item.body || item.description || 'Network activity'} · {shortDate(item.createdAt)}</small></span><ArrowRight size={14}/></button>)}</div> : <Empty>Network updates will appear here as they happen.</Empty>}</section>
        <section className="ops-panel ops-agreements"><span className="ops-agreement-icon"><Handshake size={18}/></span><div><span className="ops-eyebrow">AGREEMENTS</span><h2>{activeAgreements} active agreements</h2><p>Monitor documents and signatures across your network.</p><button className="ops-link-button" onClick={() => onNavigate('agreements')}>View agreements <ArrowRight size={14}/></button></div></section>
      </div>
    </>}
  </div>;
}
