import { ArrowRight, BadgeCheck, Compass, FileCheck2, Handshake, LockKeyhole, MoveUpRight, Wallet, Play } from 'lucide-react';
import { LAUNCH_CTA, PUBLIC_PRICING_NOTE } from './public-offer';
import { LEGAL_SUPPORT_EMAIL } from './legal-policy';
import './home-offer-details.css';

export function HomeBenefits() {
  return <section className="homeOfferSection" aria-labelledby="homeOfferTitle"><div className="homeOfferHeading reveal"><span className="eyebrow">TWO WAYS TO GROW YOUR BUSINESS</span><h2 id="homeOfferTitle">The right referral.<br/><em>On either side of the handoff.</em></h2></div><div className="homeOfferGrid"><article className="homeOfferCard reveal"><span className="homeOfferIcon"><MoveUpRight size={24}/></span><small>REFER A CLIENT</small><h3>A client you can’t serve.<br/>A fee you can still earn.</h3><p>Moving to another city? Looking for expertise outside your scope? Introduce your client to the right agent and agree a referral fee before the handoff.</p><span className="homeOfferOutcome"><Handshake size={15}/> Keep helping your client. Create a fee opportunity.</span></article><article className="homeOfferCard reveal delay1"><span className="homeOfferIcon"><Compass size={24}/></span><small>RECEIVE A REFERRAL</small><h3>Your local expertise.<br/>Their next opportunity.</h3><p>Discover buyer and seller referrals in the markets you serve. Introduce yourself, share why you’re a good fit, and connect with the referring professional.</p><a className="homeOfferOutcome" href="/marketplace">Explore the sample marketplace <ArrowRight size={15}/></a></article></div><p className="homeOfferFootnote">Planned member features · Fees depend on the signed referral terms and the transaction outcome.</p></section>;
}

export function HomeLaunchDetails({ onLaunch }) {
  return <section className="homeLaunchSection reveal" id="launch-details" aria-labelledby="homeLaunchTitle"><div className="homeLaunchIntro"><span className="homeLaunchStatus"><i/> PUBLIC PREVIEW · MEMBER ACCESS COMING SOON</span><h2 id="homeLaunchTitle">What can you do<br/><em>today?</em></h2><p>Explore how AgentReferrals works before the member marketplace opens.</p><button onClick={onLaunch} className="button buttonBlue">{LAUNCH_CTA} <ArrowRight size={16}/></button></div><div className="homeLaunchContent"><div className="homeLaunchItem"><Compass size={20}/><span><b>Explore sample referrals</b><p>See illustrative buyer and seller opportunities. No live client listings are available in the public preview.</p></span><a href="/marketplace" aria-label="Explore sample referrals"><ArrowRight size={17}/></a></div><div className="homeLaunchItem"><Play size={20}/><span><b>See the handoff in action</b><p>The interactive walkthrough shows a sample introduction, agent selection and agreement workflow.</p></span><a href="#marketplace" aria-label="Watch the referral walkthrough"><ArrowRight size={17}/></a></div><div className="homeLaunchItem"><LockKeyhole size={20}/><span><b>Member access comes next</b><p>Account creation, verification submissions, posting and applications open after launch. Clicking launch details does not create an account or join a waitlist.</p></span></div><div className="homeLaunchPricing"><Wallet size={17}/><p>{PUBLIC_PRICING_NOTE}</p></div></div></section>;
}

export function HomeTrustDetails() {
  const steps = [
    { Icon: BadgeCheck, label: '01 / VERIFICATION', title: 'Know who you’re working with.', text: 'Professionals submit license, jurisdiction and brokerage information for review. Approval is required for referral actions; a profile alone does not unlock the marketplace.' },
    { Icon: FileCheck2, label: '02 / AGREEMENTS', title: 'Agree the terms before the handoff.', text: 'Review the referral fee, fee basis, payment conditions and timing together. Complete the required signatures and retain the agreement record with the referral.' },
    { Icon: Wallet, label: '03 / PAYMENTS', title: 'Make the payment arrangement clear.', text: 'The participating professionals and brokerages handle payment under their signed terms. Public previews do not process payments or offer automatic payouts.' },
  ];
  return <section className="homeTrustSection" aria-labelledby="homeTrustTitle"><div className="homeOfferHeading reveal"><span className="eyebrow">CLARITY AT EVERY STEP</span><h2 id="homeTrustTitle">A good introduction needs<br/><em>more than a handshake.</em></h2><p>Here’s how the planned member workflow handles professional access, signed terms and payment expectations.</p></div><div className="homeTrustGrid">{steps.map(({ Icon, label, title, text }) => <article className="homeTrustCard reveal" key={label}><span className="homeOfferIcon"><Icon size={23}/></span><small>{label}</small><h3>{title}</h3><p>{text}</p></article>)}</div><div className="homeTeamNote reveal"><img src="/agentreferrals-mark.svg" alt=""/><div><b>Built by the AgentReferrals team, for thoughtful professional handoffs.</b><p>Our aim is simple: help agents serve clients beyond their own market and connect with opportunities where they work.</p></div><a href={`mailto:${LEGAL_SUPPORT_EMAIL}`}>Talk to the team <ArrowRight size={15}/></a></div></section>;
}
