import { ArrowLeft, ArrowRight, BookOpenText, CheckCircle2, ChevronRight, FileText, LockKeyhole, ShieldCheck } from 'lucide-react';
import { LEGAL_EFFECTIVE_DATE, LEGAL_POLICY_VERSION, LEGAL_SUPPORT_EMAIL } from './legal-policy';
import './legal-document.css';

const sections = {
  terms: [
    ['1. About AgentReferrals', 'AgentReferrals provides an online workspace for real-estate professionals to discover referral opportunities, submit and review applications, communicate about referrals, and prepare or manage referral agreements. In these terms, “we,” “us,” and “our” mean the AgentReferrals service operator; “you” means the person using the Services.'],
    ['2. Eligibility and your account', 'You must be legally able to enter into a binding agreement and provide accurate, current information. Keep your login credentials private, use your account yourself, and tell us promptly if you suspect unauthorized access. You are responsible for activity carried out through your account, except to the extent applicable law says otherwise. Do not create accounts for another person without authorization.'],
    ['3. Professional information and verification', 'You are responsible for keeping your name, contact details, real-estate license, jurisdiction, and brokerage information accurate. You may use the professional marketplace only in a manner permitted by the laws and professional rules that apply to you. We may ask for information reasonably needed to review professional eligibility. Government identification is requested only when required by an applicable verification policy; this service does not ask for your Social Security number in its standard onboarding flow. Approval is not a guarantee of another user’s conduct or credentials beyond the checks described in the service.'],
    ['4. Referrals and agreements between professionals', 'A referral post or application is an invitation to discuss a potential introduction; it does not by itself create a referral relationship, guarantee a transaction, or guarantee compensation. The professionals involved must review and agree to the material terms for each referral. Any referral agreement shown in the service is a separate agreement between its signing parties. Read it before signing. Do not treat a draft, application, or platform status as a substitute for that agreement or for advice from your broker or counsel.'],
    ['5. Acceptable use', 'Do not use the Services to misrepresent your identity or license, post unlawful or misleading opportunities, misuse another person’s contact or confidential information, interfere with the service, bypass access controls, or violate real-estate, privacy, advertising, fair-housing, or other applicable requirements. You must have permission to share information you submit about another person.'],
    ['6. Your content', 'You retain rights you already have in information and materials you submit. You give us permission to host, process, display, and share that content as needed to operate the Services—for example, showing an opportunity to eligible professionals, routing an application to the posting professional, or retaining a signed agreement and its audit record. This permission ends when the content is removed, except for copies we must retain for legal, security, dispute-resolution, or recordkeeping purposes.'],
    ['7. Platform availability and changes', 'We work to keep the Services useful and secure, but features may change or be unavailable from time to time. We may update these terms as the service changes. If a change is material, we will take reasonable steps to give notice before it takes effect. The “effective” date and version above identify this copy. Continued use after an updated version takes effect means acceptance only where applicable law permits.'],
    ['8. Suspension and closing an account', 'You may stop using the Services and request account closure by contacting support. We may restrict or suspend access if reasonably needed to protect users, investigate suspected misuse, comply with law, or enforce these terms. Where practical, we will explain the reason and provide a way to contact us. Some records, including completed agreements and security or audit records, may need to be retained after account closure as described in the Privacy Policy.'],
    ['9. Disclaimers', 'To the extent permitted by law, the Services are provided on an “as available” basis. We do not promise that a referral will lead to a transaction, that another user will accept an application or perform an agreement, or that information supplied by another user is complete. The Services are not legal, tax, brokerage, or compliance advice. Nothing here removes a consumer or user right that cannot legally be waived.'],
    ['10. Limits and applicable law', 'Nothing in these terms limits liability or remedies where applicable law does not allow that limitation. The law, venue, and any formal dispute process that applies will be determined by the service operator’s published business details and applicable law; this page does not create an arbitration agreement or select a governing jurisdiction.'],
    ['11. Contact', <>For questions about these terms, email <a href={`mailto:${LEGAL_SUPPORT_EMAIL}`}>{LEGAL_SUPPORT_EMAIL}</a>.</>],
  ],
  privacy: [
    ['1. What this notice covers', 'This Privacy Policy explains how AgentReferrals handles information through its website and professional referral marketplace (the “Services”). It describes the information we collect, why we use it, when it may be shared, and choices you can make. The current copy is version 1.0, effective October 2, 2026.'],
    ['2. Information you provide', 'Depending on how you use the Services, you may provide your name, email address, phone number, password credentials, profile and biography, location and service areas, real-estate license and brokerage details, professional preferences, referral posts, applications, messages, consent choices, and agreement information. If a jurisdiction-specific verification policy requires supporting evidence, you may be asked for the minimum documents needed for that review. Government ID is not automatically required and the standard onboarding flow does not collect Social Security numbers.'],
    ['3. Information created when you use the Services', 'We maintain account and verification status, referral and application activity, agreement records and signature events, consent timestamps, and support communications. The service may also receive technical information such as browser or device details, approximate network information, security events, and diagnostic logs needed to operate, protect, and troubleshoot the Services.'],
    ['4. How we use information', 'We use information to create and secure accounts; verify email and professional eligibility; show profiles and referral opportunities to relevant users; route applications and communications; prepare and retain agreements and audit histories; provide support; prevent abuse; maintain and improve the Services; and meet legal obligations. We use sensitive verification information only for the review and security purposes for which it was collected.'],
    ['5. When information is shared', 'Your professional profile and marketplace activity may be visible to other eligible users as part of the Services. When you apply to a referral or post one, information needed to evaluate and manage that opportunity may be shared with the other professionals involved. We may use service providers that help operate hosting, authentication, storage, communications, or support systems, under access limits appropriate to their work. We may also disclose information when required by law or when reasonably necessary to protect users, the Services, or legal rights. We do not sell personal information for money.'],
    ['6. Retention', 'We keep information for as long as needed to provide the Services and for legitimate operational purposes such as professional verification, dispute resolution, security, agreement records, and legal obligations. Retention periods depend on the type of record and the reason it is held. When information is no longer needed, we take reasonable steps to delete it or remove identifying details, subject to backups and records we are required or permitted to retain.'],
    ['7. Security', 'We use administrative, technical, and organizational safeguards intended to protect information, including access controls for account and verification data. No website or storage system can be guaranteed completely secure. Users should protect their passwords and promptly report suspected account or data misuse. Sensitive information should be limited to what is needed for the relevant purpose.'],
    ['8. Your choices and requests', <>You can review and update many profile details in your account. You may ask us to access, correct, or delete personal information, or close your account, by emailing <a href={`mailto:${LEGAL_SUPPORT_EMAIL}`}>{LEGAL_SUPPORT_EMAIL}</a>. We may need to verify your request and retain certain records for legal, security, agreement, or dispute reasons. Depending on where you live, additional privacy rights may apply; we will handle eligible requests under applicable law.</>],
    ['9. Cookies and local storage', 'The Services may use browser storage or similar technologies to keep you signed in, remember preferences, and protect account flows. You can manage browser storage through your browser settings, though disabling it may prevent some features from working.'],
    ['10. Children', 'The Services are designed for adult real-estate professionals and are not intended for children. Please contact us if you believe a child has provided personal information through the Services.'],
    ['11. Updates and contact', <>We may update this notice when our practices or the Services change. The latest version and effective date will appear here. Questions or privacy requests can be sent to <a href={`mailto:${LEGAL_SUPPORT_EMAIL}`}>{LEGAL_SUPPORT_EMAIL}</a>.</>],
  ],
};

export default function LegalDocument({ type = 'terms' }) {
  const isPrivacy = type === 'privacy';
  const title = isPrivacy ? 'Privacy Policy' : 'Terms of Service';
  const Icon = isPrivacy ? LockKeyhole : FileText;
  return <main className="legal-page">
    <div className="legal-glow legal-glow-a"/><div className="legal-glow legal-glow-b"/>
    <header className="legal-topbar"><a className="legal-brand" href="/"><img src="/agentreferrals-mark.svg" alt=""/><span>Agent<span>Referrals</span></span></a><a className="legal-back" href="/"><ArrowLeft size={16}/> Back to website</a></header>
    <section className="legal-hero"><span className="legal-kicker"><ShieldCheck size={15}/> AGENTREFERRALS · LEGAL</span><h1>{title}</h1><p>Clear information for a trusted professional network.</p><div className="legal-meta"><span>Effective {LEGAL_EFFECTIVE_DATE}</span><span>Version {LEGAL_POLICY_VERSION}</span><span><CheckCircle2 size={14}/> Applies to AgentReferrals Services</span></div></section>
    <div className="legal-layout"><aside className="legal-toc"><div><BookOpenText size={17}/><b>On this page</b></div>{sections[type].map(([heading], index)=><a key={heading} href={`#section-${index+1}`}><span>{String(index+1).padStart(2,'0')}</span>{heading.replace(/^\d+\.\s*/, '')}<ChevronRight size={13}/></a>)}<div className="legal-switch">{isPrivacy?<><FileText size={15}/><a href="/terms">Read Terms of Service <ArrowRight size={14}/></a></>:<><LockKeyhole size={15}/><a href="/privacy">Read Privacy Policy <ArrowRight size={14}/></a></>}</div></aside>
      <article className="legal-content"><div className="legal-content-head"><span><Icon size={18}/></span><div><small>AGENTREFERRALS</small><h2>{title}</h2></div><span className="legal-version">v{LEGAL_POLICY_VERSION}</span></div><div className="legal-notice"><ShieldCheck size={17}/><p>{isPrivacy?'We aim to collect only information needed to run accounts, referrals, and professional verification. Sensitive documents are requested only when a published jurisdiction policy requires them.':'These service terms explain how accounts and referrals work. Each referral agreement remains a separate document for the professionals who sign it.'}</p></div>{sections[type].map(([heading, body], index)=><section className="legal-section" id={`section-${index+1}`} key={heading}><span className="legal-section-num">{String(index+1).padStart(2,'0')}</span><div><h3>{heading.replace(/^\d+\.\s*/, '')}</h3><p>{body}</p></div></section>)}<footer className="legal-doc-footer"><span>© 2026 AgentReferrals</span><a href="/">Back to website <ArrowRight size={14}/></a></footer></article></div>
    <footer className="legal-site-footer"><span>AgentReferrals · Professional connections, with clarity.</span><span>Questions? <a href={`mailto:${LEGAL_SUPPORT_EMAIL}`}>{LEGAL_SUPPORT_EMAIL}</a></span></footer>
  </main>;
}
